"""Training UI.

This is the abstract class for all training UIs. Any versions of the training UI
will inherit from this class to allow interchangeability of the UI between using
command line and a tkinter GUI.

Author:
    Yvan Satyawan <y_satyawan@hotmail.com
"""
from abc import ABC, abstractmethod


class TrainingUI(ABC):
    @abstractmethod
    def __init__(self):
        """Initializes the class and stores some required values."""

    @abstractmethod
    def update_data(self, step, epoch, accuracy, loss, rate):
        """Updates the strings within the UI.

        Args:
            target (array-like): An array-like object that represents the target
                                 segmentation.
            generated (array-like): An array-like object that represents the
                                    segmentation generated by the Network.
            step (int): The current step of the training process.
            epoch (int): The current epoch of the training process.
            accuracy (float): The accuracy of the Network at the current step.
            loss (float): The loss of the Network at the current step.
            rate (float): The rate the Network is running at in steps per
                          second.
        """
        pass

    @abstractmethod
    def update_status(self, message):
        """Updates the status message within the UI.

        Args:
            message (str): The new message that should displayed.
        """
        pass

    @abstractmethod
    def set_max_values(self, total_steps, total_epochs):
        """Sets the number of steps and epochs during this training session.

        Args:
            total_steps (int): The total number of steps.
            total_epochs (int): The total number of epochs.
        """
